version: "2"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
  rboxlo:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./environment/nginx/logs:/var/log/nginx
      - ./environment/site:/var/www/data